#!/usr/bin/env python

import sys

from rqt_herox_missioneditor.missioneditor import HeroxMissionEditor
from rqt_gui.main import Main

plugin = 'rqt_herox_missioneditor'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
