#!/usr/bin/env python

import sys

from rqt_herox_dashboard.dashboard import HeroxDashboard
from rqt_gui.main import Main

plugin = 'rqt_herox_dashboard'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
